import { useMemo, useRef, useState, type FormEvent } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUpRight, BedDouble, Car, Check, Home, Instagram, KeyRound, MapPin, Menu, MessageCircle, Search, X } from "lucide-react";

type Property = { id:string; kind:string; location:string; area:number; bedrooms:number; parking:number; price:number; image:string; imageAlt:string; title:string; url:string; neighborhood:string };
const properties:Property[]=[
{id:"apt-ancuri",kind:"apartamento",location:"Ancuri · Itaitinga",neighborhood:"ancuri itaitinga",area:60,bedrooms:2,parking:1,price:165000,title:"Apartamento com varanda",image:"https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1100&q=88",imageAlt:"Sala clara de apartamento contemporâneo",url:"https://www.zapimoveis.com.br/imovel/venda-apartamento-2-quartos-com-varanda-gourmet-ancuri-itaitinga-ce-60m2-id-2746929619/"},
{id:"casa-ancuri",kind:"casa",location:"Ancuri · Itaitinga",neighborhood:"ancuri itaitinga",area:79,bedrooms:3,parking:1,price:227000,title:"Casa para viver com espaço",image:"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1100&q=88",imageAlt:"Casa contemporânea com jardim",url:"https://www.zapimoveis.com.br/imovel/venda-casa-3-quartos-ancuri-itaitinga-ce-79m2-id-2866625853/"},
{id:"casa-forquilha",kind:"casa",location:"Forquilha · Ceará",neighborhood:"forquilha mesquita jeronimo",area:173,bedrooms:4,parking:2,price:300000,title:"Casa com espaço para a família",image:"https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1100&q=88",imageAlt:"Interior acolhedor de residência contemporânea",url:"https://www.zapimoveis.com.br/imovel/venda-casa-4-quartos-centro-forquilha-ce-173m2-id-2830380939/"}
];
const phone="558532244445", allListings="https://www.zapimoveis.com.br/imobiliaria/79112/", instagramSearch="https://www.instagram.com/explore/search/keyword/?q=Fax%20Imobili%C3%A1ria";
const wa=(text:string)=>`https://wa.me/${phone}?text=${encodeURIComponent(text)}`;
const clean=(text:string)=>text.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim();
const formatMoney=(value:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(value);

export const Route=createFileRoute("/")({
  head:()=>({meta:[{title:"FAX Imobiliária | Imóveis em Fortaleza"},{name:"description",content:"Encontre seu próximo imóvel com a FAX Imobiliária. Compra, venda, aluguel e administração em Fortaleza desde 1992."},{property:"og:title",content:"FAX Imobiliária — seu próximo endereço começa aqui"},{property:"og:description",content:"Imóveis em Fortaleza com atendimento próximo há mais de 30 anos."},{property:"og:type",content:"website"}]}),
  component:HomePage,
});

function HomePage(){
 const [menu,setMenu]=useState(false),[purpose,setPurpose]=useState("venda"),[kind,setKind]=useState(""),[place,setPlace]=useState(""),[filters,setFilters]=useState({purpose:"venda",kind:"",place:""}),[name,setName]=useState(""),[contact,setContact]=useState(""),[interest,setInterest]=useState("Comprar um imóvel");
 const rail=useRef<HTMLDivElement>(null);
 const visible=useMemo(()=>properties.filter(p=>(filters.purpose==="venda")&&(!filters.kind||p.kind===filters.kind)&&(!filters.place||clean(p.location+" "+p.neighborhood).includes(clean(filters.place)))),[filters]);
 const search=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setFilters({purpose,kind,place});document.getElementById("imoveis")?.scrollIntoView({behavior:"smooth"})};
 const lead=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();window.open(wa(["Olá, vim pelo site da FAX Imobiliária.","",`Meu nome: ${name}`,`Meu telefone: ${contact}`,`Tenho interesse em: ${interest}`].join("\n")),"_blank","noopener,noreferrer")};
 const close=()=>setMenu(false);
 return <div className="fax-app">
  <div className="fax-topbar"><div className="fax-wrap fax-topbar-inner"><span><i className="fax-live-dot"/> FORTALEZA · CEARÁ</span><span>IMÓVEIS E BOAS HISTÓRIAS DESDE 1992</span><a href="tel:+558532244445">FALE COM A FAX <strong>(85) 3224-4445</strong></a></div></div>
  <header className="fax-header"><div className="fax-wrap fax-header-inner"><a className="fax-logo" href="#inicio" aria-label="FAX Imobiliária início"><span className="fax-logo-symbol">F<i>/</i></span><span className="fax-logo-word">FAX<small>IMOBILIÁRIA</small></span></a><button className="fax-menu" aria-label={menu?"Fechar menu":"Abrir menu"} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><nav className={`fax-nav ${menu?"fax-nav-open":""}`}><a href="#imoveis" onClick={close}>Imóveis</a><a href="#experiencia" onClick={close}>A FAX</a><a href="#servicos" onClick={close}>Serviços</a><a href="#contato" onClick={close}>Contato</a><a className="fax-nav-cta" href={wa("Olá, gostaria de falar com a FAX Imobiliária.")} target="_blank" rel="noreferrer">Chamar no WhatsApp <ArrowUpRight size={14}/></a></nav></div></header>
  <main>
   <section className="fax-hero" id="inicio"><div className="fax-hero-image" role="img" aria-label="Casa contemporânea cercada por vegetação"/><div className="fax-hero-overlay"/><div className="fax-wrap fax-hero-inner"><div className="fax-hero-copy"><div className="fax-eyebrow fax-eyebrow-light"><span className="fax-eyebrow-mark"/> FAX IMOBILIÁRIA · FORTALEZA</div><h1>O endereço<br/>da sua próxima<br/><em>conquista.</em></h1><p>Imóveis com a cara da sua vida. Atendimento de verdade, experiência local e cuidado em cada etapa.</p><div className="fax-actions"><a className="fax-btn fax-btn-red" href="#busca">Encontrar meu imóvel <ArrowUpRight size={15}/></a><a className="fax-hero-link" href="#experiencia">Conheça a FAX <ArrowDown size={14}/></a></div></div><div className="fax-stamp"><strong className="fax-stamp-number">34</strong><span className="fax-stamp-copy">ANOS DE<br/>FORTALEZA</span><span className="fax-stamp-rule"/><span className="fax-stamp-location">DESDE 1992</span></div><div className="fax-hero-caption"><strong>01</strong> FORTALEZA, UM LUGAR PARA PERTENCER <i/></div></div></section>
   <section className="fax-search-wrap" id="busca"><form className="fax-search-panel" onSubmit={search}><div className="fax-search-heading"><Search className="fax-search-icon"/><div><small>SEU PRÓXIMO PASSO</small><strong>Vamos encontrar?</strong></div></div><label className="fax-search-control"><span>QUERO</span><select value={purpose} onChange={e=>setPurpose(e.target.value)}><option value="venda">Comprar</option><option value="aluguel">Alugar</option></select></label><label className="fax-search-control"><span>TIPO DE IMÓVEL</span><select value={kind} onChange={e=>setKind(e.target.value)}><option value="">Todos os tipos</option><option value="apartamento">Apartamento</option><option value="casa">Casa</option><option value="comercial">Comercial</option></select></label><label className="fax-search-control fax-search-place"><span>ONDE?</span><input type="search" value={place} onChange={e=>setPlace(e.target.value)} placeholder="Bairro ou cidade"/></label><button className="fax-btn fax-btn-black fax-search-button">Buscar imóveis <ArrowRight size={15}/></button></form></section>
   <section className="fax-section fax-listings" id="imoveis"><div className="fax-wrap"><div className="fax-section-head"><div><span className="fax-eyebrow"><span className="fax-eyebrow-mark"/> SELEÇÃO FAX</span><h2>Imóveis para a vida<br/><em>que você quer viver.</em></h2></div><div className="fax-head-aside"><p>O próximo capítulo pode começar por um destes endereços.</p><a className="fax-under-link" href={allListings} target="_blank" rel="noreferrer">Ver todos os imóveis <ArrowUpRight size={14}/></a></div></div>
    <div className="fax-listing-tools"><div className="fax-result-label"><i/>{filters.kind||filters.place||filters.purpose!=="venda"?`${visible.length} IMÓVEIS ENCONTRADOS`:"OPORTUNIDADES SELECIONADAS"}</div><div className="fax-listing-arrows"><button className="fax-arrow-btn" aria-label="Rolar para a esquerda" onClick={()=>rail.current?.scrollBy({left:-360,behavior:"smooth"})}><ArrowLeft size={15}/></button><button className="fax-arrow-btn" aria-label="Rolar para a direita" onClick={()=>rail.current?.scrollBy({left:360,behavior:"smooth"})}><ArrowRight size={15}/></button></div></div>
    {visible.length?<div className="fax-property-grid" ref={rail}>{visible.map((p,i)=><article className="fax-property-card" key={p.id}><a className="fax-property-photo" href={p.url} target="_blank" rel="noreferrer" aria-label={`Abrir anúncio: ${p.title}`}><img src={p.image} alt={p.imageAlt} loading="lazy"/><span className="fax-property-status">À VENDA</span><span className="fax-photo-cta">VER IMÓVEL <ArrowUpRight size={13}/></span></a><div className="fax-property-info"><div className="fax-property-meta"><span>{p.location.toUpperCase()}</span><span>{String(i+1).padStart(2,"0")} / {String(visible.length).padStart(2,"0")}</span></div><h3>{p.title}</h3><div className="fax-property-facts"><span>{p.area} m²</span><i/><BedDouble size={13}/><span>{p.bedrooms} quartos</span><i/><Car size={13}/><span>{p.parking} vaga{p.parking>1?"s":""}</span></div><div className="fax-property-price-row"><strong>{formatMoney(p.price)}</strong><a href={wa(`Olá, tenho interesse no imóvel “${p.title}” em ${p.location}.`)} target="_blank" rel="noreferrer">Tenho interesse <ArrowUpRight size={13}/></a></div></div></article>)}</div>:<div className="fax-empty"><Search size={30}/><h3>Vamos procurar juntos?</h3><p>Essa seleção ainda não tem um imóvel com esse perfil. Fale com a equipe FAX para encontrar outras opções.</p><a className="fax-btn fax-btn-red" href={wa("Olá, procuro um imóvel com um perfil específico. Pode me ajudar?")} target="_blank" rel="noreferrer">Pedir ajuda pelo WhatsApp <ArrowUpRight size={14}/></a></div>}
    <p className="fax-listing-note">Anúncios de terceiros podem mudar. Confirme preço e disponibilidade diretamente com a equipe FAX.</p></div></section>
   <section className="fax-experience" id="experiencia"><div className="fax-experience-image"><img src="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=90" alt="Interior amplo e iluminado de uma casa contemporânea" loading="lazy"/><span className="fax-image-index">FAX · FORTALEZA / CE</span></div><div className="fax-experience-copy"><span className="fax-eyebrow fax-eyebrow-light"><span className="fax-eyebrow-mark"/> UMA HISTÓRIA DE CONFIANÇA</span><h2>De Fortaleza.<br/><em>Para o mundo.</em></h2><p>Desde 1992, a FAX ajuda pessoas a encontrar seu espaço em Fortaleza. Reunimos experiência local, atendimento próximo e uma equipe preparada para acompanhar cada decisão — da primeira conversa à entrega das chaves.</p><a className="fax-btn fax-btn-light" href="https://faximobiliaria.com.br/empresa.htm" target="_blank" rel="noreferrer">Nossa história <ArrowUpRight size={14}/></a><div className="fax-experience-years"><strong>1992</strong><span>O começo de uma história<br/>que continua crescendo.</span></div></div></section>
   <section className="fax-section" id="servicos"><div className="fax-wrap"><div className="fax-section-head"><div><span className="fax-eyebrow"><span className="fax-eyebrow-mark"/> UM BOM NEGÓCIO COMEÇA COM BOA ORIENTAÇÃO</span><h2>Seu plano. Nosso<br/><em>próximo passo.</em></h2></div><div className="fax-head-aside"><p>Experiência para quem procura um lugar. E cuidado para quem confia seu imóvel.</p></div></div><div className="fax-service-grid">
    <a className="fax-service-card" href={allListings} target="_blank" rel="noreferrer"><span className="fax-service-count">01</span><Home className="fax-service-symbol"/><h3>Comprar & vender</h3><p>Encontre boas oportunidades ou converse com a gente para vender seu imóvel.</p><span className="fax-service-action">Explorar imóveis <ArrowUpRight size={13}/></span></a>
    <a className="fax-service-card" href="https://faximobiliaria.com.br/aluguel.htm" target="_blank" rel="noreferrer"><span className="fax-service-count">02</span><KeyRound className="fax-service-symbol"/><h3>Alugar & administrar</h3><p>Locação com acompanhamento próximo para proprietários e inquilinos.</p><span className="fax-service-action">Conhecer o serviço <ArrowUpRight size={13}/></span></a>
    <a className="fax-service-card" href={wa("Olá, gostaria de solicitar uma avaliação do meu imóvel.")} target="_blank" rel="noreferrer"><span className="fax-service-count">03</span><Check className="fax-service-symbol"/><h3>Avaliar & orientar</h3><p>Uma conversa com a equipe para ajudar você a escolher o melhor caminho.</p><span className="fax-service-action">Falar com a equipe <ArrowUpRight size={13}/></span></a>
   </div></div></section>
   <section className="fax-red-cta"><div className="fax-wrap fax-red-cta-inner"><div><span className="fax-eyebrow fax-eyebrow-light">SEU IMÓVEL MERECE UMA BOA HISTÓRIA</span><h2>Vamos colocar<br/>seus planos em movimento?</h2></div><a className="fax-btn fax-btn-white" href={wa("Olá, quero conversar sobre meu imóvel.")} target="_blank" rel="noreferrer">Falar com a FAX <ArrowUpRight size={15}/></a><span className="fax-cta-watermark">FAX</span></div></section>
   <section className="fax-section fax-contact" id="contato"><div className="fax-wrap fax-contact-layout"><div className="fax-contact-copy"><span className="fax-eyebrow"><span className="fax-eyebrow-mark"/> ESTAMOS AQUI</span><h2>Uma conversa<br/>pode mudar<br/><em>tudo.</em></h2><p>Conte o que você está procurando. A equipe FAX ajuda você a encontrar o próximo passo.</p><a className="fax-contact-quick" href={wa("Olá, vim pelo site da FAX e quero conversar.")} target="_blank" rel="noreferrer"><span className="fax-quick-icon"><MessageCircle size={18}/></span><span><small>WHATSAPP / LIGAÇÃO</small><b>(85) 3224-4445</b></span><ArrowUpRight className="fax-quick-arrow" size={15}/></a><a className="fax-contact-quick" href="https://maps.google.com/?q=Rua+Jos%C3%A9+Vilar+1202+Aldeota+Fortaleza" target="_blank" rel="noreferrer"><span className="fax-quick-icon"><MapPin size={18}/></span><span><small>VISITE NOSSA UNIDADE</small><b>Rua José Vilar, 1202 · Aldeota</b></span><ArrowUpRight className="fax-quick-arrow" size={15}/></a><a className="fax-instagram-link" href={instagramSearch} target="_blank" rel="noreferrer"><Instagram size={18}/> Encontre a FAX no Instagram <span>↗</span></a></div>
    <form className="fax-lead-form" onSubmit={lead}><div className="fax-form-top"><span className="fax-eyebrow fax-eyebrow-light">ATENDIMENTO PERSONALIZADO</span><h3>Como podemos ajudar?</h3><p>Deixe seus dados. Vamos continuar essa conversa no WhatsApp.</p></div><label htmlFor="fax-name">Seu nome</label><input id="fax-name" autoComplete="name" placeholder="Como podemos chamar você?" required value={name} onChange={e=>setName(e.target.value)}/><label htmlFor="fax-phone">Seu telefone</label><input id="fax-phone" type="tel" autoComplete="tel" placeholder="(85) 99999-9999" required value={contact} onChange={e=>setContact(e.target.value)}/><label htmlFor="fax-interest">Estou procurando</label><select id="fax-interest" value={interest} onChange={e=>setInterest(e.target.value)}><option>Comprar um imóvel</option><option>Alugar um imóvel</option><option>Vender meu imóvel</option><option>Alugar meu imóvel</option><option>Administração ou avaliação</option><option>Outro assunto</option></select><button className="fax-btn fax-btn-red fax-form-submit">Continuar no WhatsApp <ArrowUpRight size={15}/></button><small className="fax-form-note">Seus dados serão usados apenas para iniciar o atendimento solicitado.</small></form>
   </div></section>
  </main>
  <footer className="fax-footer"><div className="fax-wrap"><div className="fax-footer-main"><a className="fax-logo fax-logo-inverse" href="#inicio" aria-label="FAX Imobiliária início"><span className="fax-logo-symbol">F<i>/</i></span><span className="fax-logo-word">FAX<small>IMOBILIÁRIA</small></span></a><p>Há mais de 30 anos,<br/>ajudando Fortaleza a encontrar seu lugar.</p><div className="fax-footer-social"><span>REDES</span><a href={instagramSearch} target="_blank" rel="noreferrer" aria-label="Buscar FAX no Instagram"><Instagram size={15}/></a><a href="https://www.facebook.com/search/top?q=fax%20imobili%C3%A1ria%20fortaleza" target="_blank" rel="noreferrer" aria-label="Buscar FAX no Facebook">f</a></div><a className="fax-footer-phone" href="tel:+558532244445">(85) 3224-4445 <ArrowUpRight size={14}/></a></div><div className="fax-footer-bottom"><span>© FAX Imobiliária · CRECI/CE 651-J</span><span>Fortaleza · Ceará · Brasil</span><a href="https://faximobiliaria.com.br/" target="_blank" rel="noreferrer">Site oficial ↗</a></div></div></footer>
  <a className="fax-whatsapp" href={wa("Olá, vim pelo site da FAX Imobiliária.")} target="_blank" rel="noreferrer" aria-label="Falar com a FAX pelo WhatsApp"><MessageCircle size={25} fill="white"/></a>
 </div>;
}
